#!/bin/bash

set -e


exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

#
# Get parameters from the pipeline
#
payload=$(mktemp /tmp/resource-in.XXXXXX)

# read the payload from the input file
cat > "$payload" <&0

# use our functions
source ./functions.sh

# parse payload JSON and extract properties
FYZON_URL=`extractUrl "$payload"`
PROJECT_ID=`extractProjectId "$payload"`
FORMAT=`extractFormat "$payload"`
DELIMETER=`extractDelimeter "$payload"`

COUNTRIES=`extractCountries "$payload"`
arrCountries=($COUNTRIES)

# Write debug file
cd "$1"
{
  echo "Parsed values"
  cat "$payload"
  echo $FYZON_URL
  echo $PROJECT_ID
  echo $FORMAT
  echo "$COUNTRIES[@]"
} >> debug.txt


# And now, download all the files
for i in "${COUNTRIES[@]}"
do
    fileName=`${i##*|}`
    urlDownloadFile=`buildUrlToFile "$i" "$FORMAT" "$PROJECT_ID" "$FYZON_URL" "$DELIMETER"`
    
    # and download
    curl $urlDownloadFile > fileName
done


# ...and make a JSON to be passed as a resource output
jq -n "{
  version: {
    url: $FYZON_URL
  }
}" >&3

