#!/bin/bash

set -e


exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

#
# Get parameters from the pipeline
#
payload=$(mktemp /tmp/resource-in.XXXXXX)

# read the payload from the input file
cat > "$payload" <&0

# use our functions
source ./functions.sh

# parse payload JSON and extract properties
FYZON_URL=`extractUrl "$payload"`
PROJECT_ID=`extractProjectId "$payload"`
FORMAT=`extractFormat "$PAYLOAD"`

COUNTRIES="$(jq -r '(.params.countries)' < "${payload}")"

[ -z "$COUNTRIES" ] && COUNTRIES='[]'
[ -z "$FORMAT" ] && FORMAT='properties'

# Now, download the latest translations
cd "$1"
{
  echo "Ok, data are"
  cat "$payload"
  echo $FYZON_URL
  echo $PROJECT_ID
  echo "$COUNTRIES"
} >> out.txt


for i in "${COUNTRIES[@]}"
do
    echo $i >> out.txt
done


# ...and make a JSON to be passed as a resource output
jq -n "{
  version: {
    url: $FYZON_URL
  }
}" >&3

